create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table livre (id bigint not null auto_increment, auteur varchar(255), dispo bit, editeur varchar(255), etat varchar(255), titre varchar(255), primary key (id)) engine=InnoDB;
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
create table domaine (id number(19,0) generated as identity, description varchar2(255 char), nom varchar2(255 char), primary key (id));
create table livre (id number(19,0) generated as identity, auteur varchar2(255 char), dispo number(1,0), editeur varchar2(255 char), etat varchar2(255 char), titre varchar2(255 char), primary key (id));
